export const bookAbbreviations: Record<number, string[]> = {
  1: ["gen", "ge", "gn"],
  2: ["ex", "exod", "exo"],
  3: ["lev", "le", "lv"],
  4: ["num", "nu", "nm", "nb"],
  5: ["deut", "de", "dt"],
  6: ["josh", "jos", "jsh"],
  7: ["judg", "jdg", "jg", "jdgs"],
  8: ["ruth", "rth", "ru"],
  9: ["1sam", "1sm", "1sa", "1s"],
  10: ["2sam", "2sm", "2sa", "2s"],
  11: ["1kgs", "1ki", "1k"],
  12: ["2kgs", "2ki", "2k"],
  13: ["1chr", "1ch"],
  14: ["2chr", "2ch"],
  15: ["ezra", "ezr", "ez"],
  16: ["neh", "ne"],
  17: ["est", "esth", "es"],
  18: ["job", "jb"],
  19: ["ps", "psa", "psm", "pss", "psalm"],
  20: ["prov", "pro", "prv", "pr"],
  21: ["eccl", "eccles", "ecc", "ec", "qoh"],
  22: ["song", "sos", "so", "cant"],
  23: ["isa", "is"],
  24: ["jer", "je", "jr"],
  25: ["lam", "la"],
  26: ["ezek", "eze", "ezk"],
  27: ["dan", "da", "dn"],
  28: ["hos", "ho"],
  29: ["joel", "jl"],
  30: ["amos", "am"],
  31: ["obad", "ob"],
  32: ["jonah", "jon", "jnh"],
  33: ["mic", "mc"],
  34: ["nah", "na"],
  35: ["hab", "hb"],
  36: ["zeph", "zep", "zp"],
  37: ["hag", "hg"],
  38: ["zech", "zec", "zc"],
  39: ["mal", "ml"],
  40: ["matt", "mt"],
  41: ["mark", "mrk", "mar", "mk", "mr"],
  42: ["luke", "luk", "lk"],
  43: ["john", "joh", "jhn", "jn"],
  44: ["acts", "act", "ac"],
  45: ["rom", "ro", "rm"],
  46: ["1cor", "1co"],
  47: ["2cor", "2co"],
  48: ["gal", "ga"],
  49: ["eph", "ephes"],
  50: ["phil", "php", "pp"],
  51: ["col", "co"],
  52: ["1thess", "1thes", "1th"],
  53: ["2thess", "2thes", "2th"],
  54: ["1tim", "1ti"],
  55: ["2tim", "2ti"],
  56: ["titus", "tit", "ti"],
  57: ["phlm", "phm", "pm"],
  58: ["heb"],
  59: ["jas", "jm"],
  60: ["1pet", "1pe", "1pt", "1p"],
  61: ["2pet", "2pe", "2pt", "2p"],
  62: ["1john", "1jhn", "1jn"],
  63: ["2john", "2jhn", "2jn"],
  64: ["3john", "3jhn", "3jn"],
  65: ["jude", "jd"],
  66: ["rev", "re"],
};
